cat/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView
from cat.models import MuseumObject


urlpatterns = patterns('cat.views',

    url(r'^item/$',
        ListView.as_view(
            model=MuseumObject, paginate_by=20), name='artefact_list'),
    url(r'^item/(?P<reg_num>\d+)$', 'item_detail', name='artefact_view'),



    url(r'^categories/$', 'categories_browse', name='categories_list'),

    url(r'^categories/(?P<full_slug>.+)/$', 'categories_list',
        name='categories_list'),

    url(r'^itemtype/(?P<category>.+)/(?P<item_name>.+)/$', 'item_type_list',
        name='item_type_list'),

)

parties/urls.py
from django.conf.urls.defaults import *

# place app url patterns here

urlpatterns = patterns('parties.views',
    url('browse/', 'people_aggregate', name='parties_browse'),

    url(r'^person/(?P<pk>\d+)$', 'person_detail', name="person_detail"),
    url(r'^person/(?P<pk>\d+)/(?P<item_type>\w+)$', 'person_detail', name="person_detail"),
)

cat/models.py
# -*- coding: utf-8 -*-
from django.db import models
from location.models import GlobalRegion, Country, StateProvince, RegionDistrict, Locality
import string
from smart_selects.db_fields import ChainedForeignKey


class DataDictionary(models.Model):
    definition = models.TextField(blank=True)

    class Meta:
        abstract = True


class AcquisitionMethod(DataDictionary):
    method = models.CharField(max_length=50, unique=True)
    preposition = models.CharField(help_text="Preposition to use with this "
        "acquisition method, usually 'by' or 'from'.", max_length=30)

    def __unicode__(self):
        return self.method


class LoanStatus(DataDictionary):
    status = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.status

    class Meta:
        verbose_name_plural = "Loan statuses"


class AccessStatus(DataDictionary):
    status = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.status

    class Meta:
        verbose_name_plural = "Access statuses"


class Obtained(DataDictionary):
    how = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.how

    class Meta:
        verbose_name_plural = "Source acquisition methods"


class MuseumObject(models.Model):
    """
    An object held by the museum, typically a physical object or photo
    """
    registration_number = models.IntegerField(db_index=True, unique=True)
    old_registration_number = models.CharField(max_length=50, blank=True)
    other_number = models.CharField(max_length=50, blank=True)
    reg_counter = models.CharField(max_length=50, blank=True)

    functional_category = models.ForeignKey('FunctionalCategory',
            null=True, blank=True,
            verbose_name='previous category name',
            help_text='Functional Category from the old database')
    artefact_type = models.ForeignKey('ArtefactType', verbose_name='item name')
    category = models.ManyToManyField('Category', blank=True,
            help_text='New style categories')

    storage_row = models.CharField(max_length=4, blank=True)
    storage_bay = models.CharField(max_length=4, blank=True)
    storage_shelf_drawer = models.CharField("storage shelf/drawer", max_length=4, blank=True)
#
    old_storage_section = models.CharField(max_length=4, blank=True)
    old_storage_unit = models.CharField(max_length=4, blank=True)
    old_storage_bay = models.CharField(max_length=4, blank=True)
    old_storage_shelf_box_drawer = models.CharField("old storage shelf/box/drawer", max_length=4, blank=True)

    acquisition_date = models.DateField("date acquired by museum",
            null=True, blank=True)
    acquisition_method = models.ForeignKey(AcquisitionMethod, null=True)
    loan_status = models.ForeignKey(LoanStatus, null=True,
            help_text='Is object on outwards/inwards loan')
    access_status = models.ForeignKey(AccessStatus, null=True)
    reg_info = models.TextField("registration notes", blank=True)

    registered_by = models.ForeignKey('parties.MuseumStaff', null=True, blank=True)
    registration_date = models.DateField(null=True, blank=True)

    cultural_bloc = models.ForeignKey('CulturalBloc', null=True,
            blank=True,
            help_text='Old region classification')
    place = models.ForeignKey('location.Place', null=True, db_index=True,
            help_text='Where the object is from')

# New Geo-locations data
    global_region = models.ForeignKey(GlobalRegion, blank=True, null=True,
        on_delete=models.SET_NULL)
    country = ChainedForeignKey(Country, blank=True, null=True,
        chained_field='global_region', chained_model_field='parent',
        show_all=False, on_delete=models.SET_NULL)
    state_province = ChainedForeignKey(StateProvince, blank=True, null=True,
        chained_field='country', chained_model_field='parent',
        show_all=False, on_delete=models.SET_NULL)
    region_district = ChainedForeignKey(RegionDistrict, blank=True, null=True,
        chained_field='state_province', chained_model_field='parent',
        show_all=False, on_delete=models.SET_NULL)
    locality = ChainedForeignKey(Locality, blank=True, null=True,
        chained_field='region_district', chained_model_field='parent',
        show_all=False, on_delete=models.SET_NULL)

    donor = models.ForeignKey(
            'parties.Person',
            null=True,
            blank=True,
            db_index=True,
            related_name="donated_objects",
            help_text='Main donor record')
    donor_2 = models.ForeignKey(
            'parties.Person',
            null=True,
            blank=True,
            related_name="donated_objects_2",
            verbose_name="2nd recorded donor (historic/wrong)",
            help_text='2nd Imported donor record, possibly historic')
    how_donor_obtained = models.ForeignKey(Obtained, null=True,
            related_name='donor_obtained')
    ## TODO: when_donor_obtained should be DateField
    ### But contains some imprecise dates
    when_donor_obtained = models.CharField(max_length=50, blank=True,
        help_text="Please use the following format: <em>YYYY-MM-DD</em>.")

    photographer = models.CharField(max_length=100)
    collector = models.ForeignKey(
            'parties.Person',
            null=True,
            blank=True,
            db_index=True,
            related_name="collected_objects")
    collector_2 = models.ForeignKey(
            'parties.Person',
            null=True,
            blank=True,
            verbose_name="2nd recorded collector (historic/wrong)",
            related_name="collected_objects_2")
    how_collector_obtained = models.ForeignKey(Obtained, null=True,
            related_name="collector_obtained")
    when_collector_obtained = models.CharField(max_length=50, blank=True,
            help_text="Please use the following format: <em>YYYY-MM-DD</em>.")

    source = models.CharField(max_length=50)
    how_source_obtained = models.ForeignKey(Obtained, null=True,
            related_name='source_obtained')

    maker = models.ForeignKey('parties.Person', null=True, blank=True, related_name='created_items')
    old_maker = models.ForeignKey('parties.Maker', null=True, blank=True, related_name='old_maker')
    manufacture_technique = models.CharField(max_length=200, blank=True)
    creation_date = models.DateField(null=True, blank=True)
    site_name_number = models.CharField(max_length=150, blank=True)
    raw_material = models.CharField(max_length=150, blank=True)
    indigenous_name = models.CharField(max_length=100, blank=True)
    recorded_use = models.CharField(max_length=300, blank=True)
    assoc_cultural_group = models.CharField(max_length=100, blank=True)
    exhibition_history = models.TextField(blank=True)

    category_illustrated = models.CharField(max_length=100, blank=True)
    artefact_illustrated = models.CharField(max_length=100, blank=True)

    description = models.TextField(blank=True)

    is_public_comment = models.BooleanField(default=False,
            verbose_name='public research notes',
            help_text='Can research notes be shown publicly')
    comment = models.TextField(blank=True,
            verbose_name="research notes",)
    private_comment = models.TextField(
            blank=True,
            help_text="Only visible to staff")
    significance = models.TextField("statement of significance",
            blank=True)

    width = models.IntegerField(null=True, blank=True,
            help_text="millimeters")
    length = models.IntegerField(null=True, blank=True,
            help_text="millimeters")
    height = models.IntegerField(null=True, blank=True,
            help_text="millimeters")
    depth = models.IntegerField(null=True, blank=True,
            help_text="millimeters")
    circumference = models.IntegerField(null=True, blank=True,
            help_text="millimeters")

    longitude = models.FloatField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)

    record_status = models.ForeignKey('RecordStatus', null=True, blank=True,
            help_text='Record status (eg, "Fix public data", "Check '
            'copyright", etc)')

    related_documents = models.ManyToManyField(
            'mediaman.Document',
            null=True, blank=True)

    three_d_link = models.CharField(max_length=255, blank=True,
        help_text="Link to 3D representation of this item")

    public = models.BooleanField(default=True, db_index=True)

    def dimensions(self):
        '''Returns textual dimensions for the item

        Combining length, width, height, depth, circumference
        '''
        dims = [self.length, self.width, self.height,
                self.depth, self.circumference]
        dims = [str(d / 10) for d in dims if d != None]
        s = string.join(dims, " x ")
        return s + " cm" if s else ''

    def categories(self):
        return ', '.join(str(c) for c in self.category.all())

    @models.permalink
    def get_absolute_url(self):
        return ('artefact_view', [str(self.registration_number)])

    class Meta:
        ordering = ['registration_number']

    def __unicode__(self):
        return "%s: %d" % (self.artefact_type, self.registration_number)

    def public_images(self):
        return self.artefactrepresentation_set.filter(public=True)

    def get_location(self):
        if self.locality and self.locality.latitude:
            return self.locality
        if self.region_district and self.region_district.latitude:
            return self.region_district
        if self.state_province and self.state_province.latitude:
            return self.state_province
        if self.country and self.country.latitude:
            return self.country
        if self.global_region and self.global_region.latitude:
            return self.global_region
        return None

    @staticmethod
    def autocomplete_search_fields():

parties/models.py
from django.db import models


class Person(models.Model):
    """
    A collector or photographer who has contributed to the museum
    """
    name = models.CharField(help_text="Used internally and for sorting",
        unique=True, max_length=200)
    display_name = models.CharField(help_text="For display purposes",
        max_length=200)
    comments = models.TextField(blank=True)
    related_documents = models.ManyToManyField('mediaman.Document',
            related_name='related_people', blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('person_detail', [str(self.id)])

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "people"

    @staticmethod
    def autocomplete_search_fields():
        return ("name__iexact",)


class Maker(models.Model):
    """A person or entity who created an item in the collection"""
    name = models.CharField(max_length=200, unique=True)
    comment = models.TextField(blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('maker_detail', [str(self.id)])

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return ("name__iexact",)


class Client(models.Model):
    name = models.CharField(max_length=200)
    organisation = models.CharField(blank=True, max_length=80)
    position = models.CharField(blank=True, max_length=80)
    address = models.TextField(blank=True)
    town_suburb = models.CharField(blank=True, max_length=80)
    state = models.CharField(blank=True, max_length=30)
    postcode = models.CharField(blank=True, max_length=10)
    country = models.CharField(blank=True, max_length=50)

    phone1 = models.CharField(blank=True, max_length=20)
    phone2 = models.CharField(blank=True, max_length=20)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return ("name__iexact",)


class MuseumStaff(models.Model):
    name = models.CharField(max_length=200, unique=True)
    comments = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Museum staff"
        ordering = ['name']

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return ("name__iexact",)

parties/forms.py
from django import forms

# place form definition here

parties/views.py
from django.shortcuts import render
from parties.models import Person
from django.shortcuts import get_object_or_404
from utils.utils import do_paging


def people_aggregate(request, template_name='parties/datatables.html'):
    people = Person.objects.raw("""
        select id, display_name, name,
          (select count(id) from cat_museumobject where donor_id = parties_person.id and public = true) as donated_count,
          (select count(id) from cat_museumobject where collector_id = parties_person.id and public = true) as collected_count,
          (select count(id) from cat_museumobject where maker_id = parties_person.id and public = true) as created_count,
          (select count(mediaman_document.id) from mediaman_document, parties_person_related_documents where person_id = parties_person.id and mediaman_document.id = document_id and public = true) as documents_count
        from parties_person
        """)
    return render(request, template_name,
            {'person_list': people})


def person_detail(request, pk, item_type='default', template_name='parties/person_detail.html'):

    person = get_object_or_404(Person, pk=int(pk))

    mapping = {'docs': ('related_documents', 'Related documents', person.related_documents.filter(public=True).count()),
               'created': ('created_items', 'Created items', person.created_items.filter(public=True).count()),
               'collected': ('collected_objects', 'Collected items', person.collected_objects.filter(public=True).count()),
               'donated': ('donated_objects', 'Donated items', person.donated_objects.filter(public=True).count())}

    if item_type == 'default':
        # Select max count type
        item_count = -1
        for k, v in mapping.items():
            if v[2] > item_count:
                item_count = v[2]
                item_type = k

    # output types in correct order
    types = [(key, mapping[key][1], mapping[key][2]) for key in ('docs', 'created', 'collected', 'donated')]

    if item_type in mapping.keys():
        items = getattr(person, mapping[item_type][0]).select_related().filter(public=True
            ).prefetch_related('category', 'country', 'global_region', 'artefactrepresentation_set'
            ).extra(
                select={'public_images_count': 'select count(*) from mediaman_artefactrepresentation a WHERE a.artefact_id = cat_museumobject.id AND a.public'}
                ).order_by('-public_images_count', 'registration_number')

    else:
        items = []

    objects = do_paging(request, items)

    related_documents = person.related_documents.filter(public=True)

    return render(request, template_name, {
        'person': person,
        'objects': objects,
        'related_documents': related_documents,
        'types': types,
        'item_type': item_type,
        'item_name': mapping[item_type][1]
        })


def person_objects(request):
    pass

templates/parties/datatables.html
{% extends "base_wide.html" %}

{% block title %}Browse People | {{block.super}}{% endblock %}
{% block content %}

<h1>People</h1>

<ul id="people-type-filter" class="nav nav-tabs">
    <li class="active"><a href="#all">All</a></li>
    <li><a href="#makers">Makers</a></li>
    <li><a href="#donors">Donors</a></li>
    <li><a href="#collectors">Collectors</a></li>
</ul>

<table id="people-table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Documents</th>
            <th>Created</th>
            <th>Donated</th>
            <th>Collected</th>
        </tr>
    </thead>
    <tbody>
{% for person in person_list %}
        <tr>
            <td><a href="{{ person.get_absolute_url}}">{{ person.name }}</a></td>
            <td>{{ person.documents_count }}</td>
            <td>{{ person.created_count }}</td>
            <td>{{ person.donated_count }}</td>
            <td>{{ person.collected_count }}</td>
        </tr>
{% endfor %}
    </tbody>
</table>

{% endblock content %}

{% block javascript %}
{{block.super}}
<script type="text/javascript" language="javascript" src="{{STATIC}}datatables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        var hash = window.location.hash;
        if (hash !== '') {
            $('#people-type-filter li').removeClass('active');
            $('#people-type-filter li a[href="'+hash+'"]').parent().addClass('active')
        }

        $('#people-type-filter a').click(function() {
            $('#people-type-filter li').removeClass('active');
            $(this).parent().addClass('active');

            /* redraw table with new filter */
            oTable.fnDraw();
        });

        $.fn.dataTable.ext.afnFiltering.push(
            function( oSettings, aData, iDataIndex ) {
                var curFilter = $('#people-type-filter .active').text();
                if (curFilter === 'All') {
                    return true;
                } else if (curFilter === 'Makers') {
                    return aData[2] > 0;
                } else if (curFilter === 'Donors') {
                    return aData[3] > 0;
                } else if (curFilter === 'Collectors') {
                    return aData[4] > 0;
                }

                return true;

            }
        );

        var oTable = $('#people-table').dataTable( {
//            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "bLengthChange": false,
            "iDisplayLength": 20,
//        "sScrollY": "600px",
//        "bPaginate": false,
//        "bScrollCollapse": true,
            "bStateSave": true,
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "sPaginationType": "full_numbers"

        } );
    });
</script>

{% endblock javascript %}

templates/parties/maker_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="float:right;font-size: 80%;">
    {% if user.is_staff %}
        <a href={% url admin:parties_maker_change maker.id %}>Admin</a>
    {% endif %}
</div>
<h1>{{ maker.name }}</h1>

<p>{{ maker.comments }}</p>


<div class="span-12">
<h2>Created objects</h2>
{% for mo in maker.museumobject_set.all %}

<a href="{{mo.get_absolute_url}}">{{mo.registration_number}} {{mo.artefact_type}}</a>
<br>
{% endfor %}
</div>


{% endblock %}

templates/parties/person.html
{% extends "base_generic.html" %}

{% block content %}

<h1>People</h1>
<div class="row">
<div class="span3">
<h2><a href="{% url maker_list %}">Makers</a></h2>
</div>

<div class="span3">
<h2><a href="{% url donor_list %}">Donors</a></h2>
</div>

<div class="span3">
<h2><a href="{% url collector_list %}">Collectors</a></h2>
</div>

</div><!-- row -->

{% endblock %}

templates/parties/person_detail.html
{% extends "base_wide.html" %}

{% block title %}{{ person.display_name }} | {{block.super}}{% endblock %}

{% block content %}

{% if user.is_staff %}
<div style="float:right;font-size: 80%;">
    {% if user.is_staff %}
        <a href={% url admin:parties_person_change person.id %}>Admin</a>
    {% endif %}
</div>
{% endif %}

<div class="breadcrumbs">
    <a href="{% url parties_browse %}">People</a> >
</div>

<h1>{{ person.display_name }}</h1>

<p class="person-comments">{{ person.comments }}</p>

<ul id="people-type-filter" class="nav nav-tabs">
{% for type in types %}
    <li{% if type.0 == item_type %} class="active"{%endif%}><a href="{% url parties.views.person_detail pk=person.id item_type=type.0 %}">{{type.1}} ({{type.2}})</a></li>
{% endfor %}
</ul>


{% if item_type == 'docs' %}
<table id="item-listing-table">
    <tr><th></th><th>Document</th></tr>
    {% for doc in related_documents %}
    <tr><td></td>
        <td><a href="{{doc.document.url}}">{{doc.name}}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}

    {% include "snippets/paged_object_list.html" %}
{% endif %}






{% endblock %}