cat/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView
from cat.models import MuseumObject


urlpatterns = patterns('cat.views',

    url(r'^item/$',
        ListView.as_view(
            model=MuseumObject, paginate_by=20), name='artefact_list'),
    url(r'^item/(?P<reg_num>\d+)$', 'item_detail', name='artefact_view'),



    url(r'^categories/$', 'categories_browse', name='categories_list'),

    url(r'^categories/(?P<full_slug>.+)/$', 'categories_list',
        name='categories_list'),

    url(r'^itemtype/(?P<category>.+)/(?P<item_name>.+)/$', 'item_type_list',
        name='item_type_list'),

)

location/urls.py
from django.conf.urls.defaults import *

from django.views.generic import ListView
from location.models import Place

urlpatterns = patterns('location.views',

    url(r'^places$', 'view_places', name='view_places'),
    url(r'^tree_view$', 'tree_view', name='tree_view'),


    url(r'^(?P<loctype>[\w ]+)-(?P<id>\d+)$', 'view_geoloc', name='view_geoloc'),
#    url(r'^(?P<global_region>[\w_].)/$', 'view_geoloc', name='view_geoloc'),
#    url(r'^(?P<global_region>[\w_].)/(?P<country>[\w_].)/$', 'view_geoloc', name='view_geoloc'),

    url(r'^$',
        ListView.as_view(
            model=Place), name='place_list'),
    url(r'^kml$', 'place_kml', name='place_kml'),
    url(r'^json$', 'place_json', name='place_json'),
    url(r'^(?P<place_id>\d+)$', 'place_detail', name='place_detail'),

    url(r'^dups$', 'place_duplicates', name='place_duplicates'),
    url(r'^gn/(\d+)$', 'place_geoname'),

)

location/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.template.defaultfilters import slugify
from exceptions import IllegalMove, SameLevelMove, WrongLevelMove


slug_length = 50


class LocationBase(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(help_text='Unique identifier. May be used in URLs.', max_length=slug_length)
    description = models.CharField(max_length=255, blank=True)

    gn_name = models.CharField(max_length=100,
            help_text="GeoNames Name", blank=True)
    gn_id = models.CharField(max_length=20,
            help_text="GeoNames ID", blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        abstract = True

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)[:slug_length]
        super(LocationBase, self).save(*args, **kwargs)

    def get_kml_coordinates(self):
        return "%s,%s,0" % (self.longitude, self.latitude)

    @models.permalink
    def get_absolute_url(self):
        #import ipdb; ipdb.set_trace()
        contenttype = ContentType.objects.get_for_model(self).model
        return ('view_geoloc', [str(contenttype), str(self.id)])

    def get_parents(self):
        if hasattr(self, 'parent'):
            parent = self.parent
            return parent.get_parents() + [parent]
        else:
            return []

    def moveto_parent(self, new_parent):
        self._validate_move(new_parent)
        return self._perform_move(new_parent)

    def _validate_move(self, new_parent):
        if not hasattr(self, 'parent'):
            # Top level of tree, cannot move
            raise IllegalMove()

        if type(self) == type(new_parent):
            # Parent cannot be of same type
            raise SameLevelMove

        parent_field = self._meta.get_field_by_name('parent')[0]
        req_parent_type = parent_field.rel.to

        if req_parent_type != type(new_parent):
            # new_parent is wrong type for this class
            raise WrongLevelMove

    def _perform_move(self, new_parent):
        # Check for conflicting children and merge if they exist
        if hasattr(new_parent, 'children') and \
            new_parent.children.filter(slug=self.slug):

            to_merge = new_parent.children.get(slug=self.slug)
            return self.merge(to_merge, self)
        else:
            # Simple move
            self.parent = new_parent
            self.save()

            # Update museumobjects
            field_changes = calc_field_changes(self)
            self.museumobject_set.update(**field_changes)
            return self

    @staticmethod
    def merge(target, old):
        if hasattr(old, 'children'):
            # Deal with all the children of old
            targets_children = [child.slug for child in target.children.all()]

            for child in old.children.all():
                if child.slug in targets_children:
                    # Need to merge
                    match = target.children.get(slug=child.slug)
                    LocationBase.merge(match, child)
                else:
                    # Simply move child
                    child.parent = target
                    child.save()

                    changes = calc_field_changes(target)
                    child.museumobject_set.update(**changes)

        # now that old has no children
        # Actually merge the two
        changes = calc_field_changes(target)
        old.museumobject_set.update(**changes)
        if old.museumobject_set.exists():
            raise Exception
        else:
            old.delete()

        return target


def find_mo_field_name(element):
    return element._meta.concrete_model.museumobject_set.\
            related.field.name


def calc_field_changes(element):
    """
    Walk up the tree of geo-locations, finding the new parents

    These will be set onto all the museumobjects.
    """
    fieldname = find_mo_field_name(element)
    field_changes = {fieldname: element.id}
    if hasattr(element, 'parent'):
        field_changes.update(
            calc_field_changes(element.parent))
    return field_changes


class GlobalRegion(LocationBase):
    icon_path = models.CharField(max_length=255, blank=True,
        help_text="Relative path to icon")
    icon_title = models.CharField(max_length=255, blank=True,
        help_text="Icon title, displayed on browse page")

    class Meta(LocationBase.Meta):
        pass


class Country(LocationBase):
    parent = models.ForeignKey(GlobalRegion, related_name='children',
        verbose_name='Global region', on_delete=models.PROTECT)

    class Meta(LocationBase.Meta):
        verbose_name_plural = 'countries'
        unique_together = ('parent', 'slug')


class StateProvince(LocationBase):
    parent = models.ForeignKey(Country, related_name='children',
        verbose_name='Country', on_delete=models.PROTECT)

    class Meta(LocationBase.Meta):
        unique_together = ('parent', 'slug')


class RegionDistrict(LocationBase):
    parent = models.ForeignKey(StateProvince, related_name='children',
        verbose_name='State/province', on_delete=models.PROTECT)

    class Meta(LocationBase.Meta):
        unique_together = ('parent', 'slug')


class Locality(LocationBase):
    parent = models.ForeignKey(RegionDistrict, related_name='children',
        verbose_name='Region/district', on_delete=models.PROTECT)

    class Meta(LocationBase.Meta):
        verbose_name_plural = 'localities'
        unique_together = ('parent', 'slug')


class Place(models.Model):
    country = models.CharField(max_length=30, blank=True)
    region = models.CharField(max_length=40, blank=True)
    australian_state = models.CharField(max_length=20, blank=True)
    name = models.CharField(max_length=150)

    is_corrected = models.BooleanField(default=False,
            help_text="Has someone manually"
            "moved the marker to it's correct location.")
    gn_name = models.CharField(max_length=100,
            help_text="GeoNames Name", blank=True)
    gn_id = models.CharField(max_length=20,
            help_text="GeoNames ID", blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    class Meta:
        ordering = ["id"]

    def __unicode__(self):
        return ' > '.join([self.country, self.region, self.name])

    @models.permalink
    def get_absolute_url(self):
        return ('place_detail', [str(self.id)])

    def get_geonames_url(self):
        if self.gn_id:
            return "http://www.geonames.org/%s" % self.gn_id
        else:
            return False

    def get_kml_coordinates(self):
        return "%s,%s,0" % (self.longitude, self.latitude)

    def geocode_net(self, force=False):
        """
        Lookup the latitude and longitude of this place with GeoNames

        Place must be saved after use. Set `force` to re-lookup the location.

        Can take a few seconds to return, since this uses a network request.
        """
        if self.gn_id and not force:
            return
        from utils import geocoders
        geonames = geocoders.GeoNamesWithId()
        place, geonameId, (lat, lng) = geonames.geocode('%s, %s' %
                                                (self.name, self.country,),
                                                exactly_one=False)[0]
        self.gn_name = place
        self.gn_id = geonameId
        self.latitude = lat
        self.longitude = lng

    @staticmethod
    def autocomplete_search_fields():
        return ("country__icontains", "region__icontains",
                "australian_state__icontains", "name__icontains")


class Region(models.Model):
    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

location/forms.py
from django import forms

# place form definition here

location/views.py
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.utils.xmlutils import SimplerXMLGenerator
from models import Place, Region
from models import Locality
from models import GlobalRegion
from utils.utils import do_paging, split_list
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType
import json


def place_detail(request, place_id):
    """
    Lookup a ``Place`` based on its id. Pagination its objects.
    """
    place = get_object_or_404(Place, pk=place_id)
    try:
        region = Region.objects.get(name=place.region)
    except:
        region = None
    place_objects = place.museumobject_set.filter(public=True)

    objects = do_paging(request, place_objects)

    return render(request, "location/place_detail.html",
            {'place': place, 'objects': objects,
             'region': region})


def place_json(request, encoding='utf-8', mimetype='text/plain'):
    places = Locality.objects.exclude(
            latitude=None).annotate(Count('museumobject')).values(
            'id', 'name', 'latitude', 'longitude',
            'museumobject__count')
    return HttpResponse(json.dumps(list(places), indent=2))


def place_kml(request, encoding='utf-8', mimetype='text/plain'):
    """
    Write out all the known places to KML
    """
#    mimetype = "application/vnd.google-earth.kml+xml"
#    mimetype = "text/html"
    places = Locality.objects.exclude(
            latitude=None).annotate(Count('museumobject'))

    response = HttpResponse(mimetype=mimetype)
    handler = SimplerXMLGenerator(response, encoding)

    handler.startDocument()
    handler.startElement(u"kml",
            {u"xmlns": u"http://www.opengis.net/kml/2.2"})
    handler.startElement(u"Document", {})

    for place in places:
        place_url = request.build_absolute_uri(place.get_absolute_url())
        handler.startElement(u"Placemark", {})
        handler.addQuickElement(u"name",
                "%s (%s)" % (place.name, place.museumobject__count))
        handler.addQuickElement(u"description",
                '<a href="%s">%s</a>' % (place_url, place.__unicode__()))
        handler.startElement(u"Point", {})
        handler.addQuickElement(u"coordinates", place.get_kml_coordinates())
        handler.endElement(u"Point")
        handler.endElement(u"Placemark")

    handler.endElement(u"Document")
    handler.endElement(u"kml")

    return response


def place_duplicates(request):
    '''
    Used for finding duplicate places, by Geoname ID
    '''
    places = Place.objects.values(
            'gn_id').order_by().annotate(
                    count=Count('gn_id')).filter(count__gt=1)
    return render(request, "location/place_dups_list.html",
            {'places': places})


def place_geoname(request, geoname_id):
    places = Place.objects.filter(gn_id=geoname_id)
    return render(request, "location/place_geoname.html", {'places': places})


def tree_view(request):
    global_regions = GlobalRegion.objects.all()
    return render(request, "location/tree_view.html",
        {'global_regions': global_regions})


def find_location(model_type, id):
    element_type = ContentType.objects.get(app_label='location', model=model_type)
    return element_type.get_object_for_this_type(id=id)


def view_places(request):
    grs = GlobalRegion.objects.exclude(icon_path="").prefetch_related('children')
    d = dict((g.name, g) for g in grs)
    grs = [d['Australia'], d['Pacific'], d['Asia'], d['Europe'], d['Americas'], d['Africa'],
        d['Middle East']]

    kml_url = request.build_absolute_uri(reverse('place_kml'))

    return render(request, 'location/map.html',
        {'global_regions': grs,
         'kml_url': kml_url})


def view_geoloc(request, loctype, id, columns=3):

    try:
        geolocation = find_location(loctype, id)
    except ObjectDoesNotExist:
        raise Http404

    items = geolocation.museumobject_set.select_related().filter(public=True
        ).prefetch_related('category', 'country', 'global_region'
        ).extra(
            select={'public_images_count': 'select count(*) from mediaman_artefactrepresentation a WHERE a.artefact_id = cat_museumobject.id AND a.public'}
            ).order_by('-public_images_count', 'registration_number')

    children = []
    if hasattr(geolocation, 'children'):
        children = geolocation.children.all()

    objects = do_paging(request, items)

    return render(request, 'location/geolocation.html',
        {'geolocation': geolocation,
         'objects': objects,
         'num_children': len(children),
         'children': split_list(children, parts=columns)})

templates/location/geolocation.html
{% extends "base_wide.html" %}
{% load uqam %}

{% block title %}{{geolocation.name}} | {{block.super}}{% endblock %}


{% block headextra %}
{% if geolocation.latitude %}
<meta name="geo.position" content="{{geolocation.latitude}};{{geolocation.longitude}}" />
{% endif %}
{% endblock headextra %}


{% block content %}

<div class="breadcrumbs">
    <a href="{% url view_places %}">Places</a>
    {% for parent in geolocation.get_parents %}
     &rsaquo; <a href="{{parent.get_absolute_url}}"> {{parent.name}}&nbsp;</a>
    {% endfor %}
</div><!-- /breadcrumbs -->

{% if user.is_staff %}
<div style="float:right;font-size: 80%;">
  <a href="{{ geolocation|admin_change_link }}">Admin</a>
</div>
{% endif %}


{% if geolocation %}
    <h1>{{geolocation.name}}</h1>

    {% if geolocation.description %}
    <p class="placeDesc">{{ geolocation.description }}</p>
    {% endif %}
{% endif %}

{% if children %}
<div class="places-subplaces">
    {% if num_children > 30 %}
        <div class="show-all">
            <button onclick="$('.places-subplaces ul.column').toggle();" class="btn">Show all: {{num_children}} localities</button>
        </div>
    {% endif %}
    {% for column in children %}
    <ul class="column {% if num_children > 30 %}hidden{% endif %}">
        {% for child in column %}
        <li><a href="{{child.get_absolute_url}}">{{child.name}}</a></li>
        {% endfor %}
    </ul>
    {% endfor %}
</div><!-- /places-subplaces -->
{% endif %}

{% if objects %}
    {% include "snippets/paged_object_list.html" %}
{% endif %}

{% endblock content %}

templates/location/jstree.html
{% extends "admin/base_site.html" %}

{% load static %}

<!-- BREADCRUMBS -- >
{% block breadcrumbs %}
    {% if not is_popup %}
        <ul class="grp-horizontal-list">
            <li><a href="{% url admin:index %}">Home</a></li>
            <li>{{ title }}</li>
        </ul>
    {% endif %}
{% endblock %}

<!-- CONTENT -->
{% block content %}
<script type="text/javascript" src="{% static 'jquery-1.7.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jstree/jquery.jstree.js' %}"></script>

<script type="text/javascript">

$(function() {
    jQuery(document).ajaxSend(function(event, xhr, settings) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function sameOrigin(url) {
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    function safeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
});
{% comment %}
    $("#geolocations").jstree({
        "core": {
            "animation": 0
        },
        "plugins": ["themes", "html_data"]
    });
{% endcomment %}
    $("#geolocations").bind("move_node.jstree", function(event, data) {
        var tree = data.inst; /* the actual tree instance */
        var args = data.args; /* arguments passed to the function */
        var rslt = data.rslt; /* any data the function passed to the event */
        var rlbk = data.rlbk; /* an option rollback object - not always present */
        var tree = $.jstree._reference('#geolocations');

        data.rslt.o.each(function (o) {
            // send request
            var obj = data.rslt.o[o];
            var np = args[0].np[0];
            var op = args[0].op[0];
            var request = $.ajax({
                "url": "{% url admin:move_element %}",
                "type": "POST",
                "data": {
                    "obj": obj.id,
                    "new-parent": np.id
                }
            });
            request.done(function() {
                tree.refresh();
            });
            request.fail(function(xhr, textStatus) {
                alert("Error: " + xhr.responseText);
                $.jstree.rollback(data.rlbk);
            });

        })
    }).bind("create.jstree", function(event, data) {
        var node = data.rslt.obj[0];
        var parent_id = data.rslt.parent.attr("id");
        var name = data.rslt.name;
        var type = data.rslt.obj.attr('rel')
        var tree = $.jstree._reference('#geolocations');
        $.ajax({
            "url": "{% url admin:create_element %}",
            "type": "POST",
            "data": {
                "name": name,
                "type": type,
                "parent": parent_id
            }
        }).done(function(xhr) {
            $(data.rslt.obj).attr("id", type + "-" + xhr.id);
            tree.set_text(node, name + " (0)");

        }).fail(function(xhr, textStats) {
            $.jstree.rollback(data.rlbk);
            alert(xhr.responseText);
        });
    }).bind("rename.jstree", function(event, data) {
        var node = data.rslt.obj;
        var tree = $.jstree._reference('#geolocations');
        $.ajax({
            "url": "{% url admin:rename_element %}",
            "type": "POST",
            "data": {
                "obj": node.attr('id'),
                "new-name": data.rslt.new_name
            }
        }).error(function(xhr) {
            tree.refresh();
        }).done(function(xhr) {
            if (xhr.error) {
                var name = data.rslt.old_name + " (" + xhr.count + ")";
                tree.set_text(node, name);
                alert("Error: " + xhr.message);
            } else {
                var name = xhr.new_name + " (" + xhr.count + ")";
                tree.set_text(node, name);
            }
        });
    }).bind("delete_node.jstree", function(event, data) {
        var node = data.rslt.obj;
        var tree = $.jstree._reference('#geolocations');
        tree = this;
        $.ajax({
            "url": "{% url admin:delete_element %}",
            "type": "POST",
            "data": {
                "obj": node.attr('id')
            }
        }).fail(function(xhr, textStatus) {
            $.jstree.rollback(data.rlbk);
            alert('Unable to delete: ' + xhr.responseText);
        });
    }).bind("dblclick.jstree", function (e, data) {
        var node = $(e.target).closest("li");
        var id = node[0].id; //id of the selected node
        var url = "/place/" + id;
        window.open(url);
    });
    $("#geolocations").jstree({
        "core": {
            "animation": 0
        },
        "json_data": {
            "ajax": {
                "url": function(node) {
                    if (node === -1) {
                        return "{% url admin:find_children %}";
                    } else {
                        return "{% url admin:find_children %}" + node.attr('id');
                    }
                }
            }
        },
        "types": {
            "valid_children": ["globalregion"],
            "types": {
                "globalregion": {
                    "valid_children": ["country"],
                    "icon": {"image": "/static/geolocations_icons.png"}
                },
                "country": {
                    "valid_children": ["stateprovince"],
                    "icon": {"image": "/static/geolocations_icons.png",
                            "position": "-16px 0px"}
                },
                "stateprovince": {
                    "valid_children": ["regiondistrict"],
                    "icon": {"image": "/static/geolocations_icons.png",
                            "position": "-32px 0px"}
                },
                "regiondistrict": {
                    "valid_children": ["locality"],
                    "icon": {"image": "/static/geolocations_icons.png",
                            "position": "-48px 0px"}
                },
                "locality": {
                    "valid_children": "none",
                    "icon": {"image": "/static/geolocations_icons.png",
                            "position": "-64px 0px"}
                }
            }
        },
        "crrm": {
            "move": {
                "check_move": function(m) {
                    $('#status').html("Position: " + m.p + " Calc Pos: " + m.cp + " m.r: " + m.r + " m.np: " + m.np);
                    var newp = m.np;
                    var oldp = m.op;
                    // check if the movement is to a different parent
                    if (newp[0].id != oldp[0].id && m.cp === 0) {
                        return true;
                    }
                    return false;
                },
                "default_position": "first"
            }
        },
        "dnd": {
            "drop_target": false,
            "drag_target": false
        },
        "ui": {
            "disable_selecting_children": true
        },
        "contextmenu": {
            "items": function customMenu(node) {
                var items = {
                    "view_admin": {
                        "label": "Edit in Admin",
                        "action": function(obj) {
                            var vals = obj.attr('id').split('-');
                            var type = vals[0];
                            var id = vals[1];
                            var url = "/admin/location/" + type + "/" + id + "/";
                            window.open(url);
                        }
                    },
                    "create": {
                        "label": "Create",
                        "action": function (obj) {
                            this.create(obj);
                        }, "_disabled": false,
                        "_class": "add",
                        "separator_before": false
                    },
                    "rename": {
                        "label": "Rename",
                        "action": function (obj) {
                            var name = this.get_text(obj);
                            name = name.replace(/ \(\d+\)$/, '');
                            this.set_text(obj, name);
                            this.rename(obj);
                        }, "_disabled": false,
                        "_class": "rename",
                        "separator_before": false
                    },
                    "delete": {
                        "label": "Delete",
                        "action": function (obj) {
                            this.remove(obj);
                        }, "_disabled": false,
                        "_class": "delete",
                        "separator_before": true
                    }
                };
                if (!this._is_loaded(node) || this._get_children(node).length > 1) {
                    items['delete']._disabled = true;
                }

                return items;
            }
        },
        "themes": {
            "theme": "apple"
        },
        "plugins": [ "themes", "json_data", "dnd", "types", "crrm", "contextmenu", "ui"]
    });
});


</script>

    

<div id="geolocations">

</div>

<div id="controls">
    <a href="#" onclick="$.jstree._reference('#geolocations').refresh();return false;">Refresh</a>
    <a href="{% url admin:location_globalregion_add %}">Add Global Region</a>
</div>
<div id="status">
</div>

<style>
#legend ins {
    background-image: url(/static/geolocations_icons.png);
    height: 16px;
    width: 16px;
}
#legend ins[rel="country"] {
    background-position: -16px 0px;
}
#legend ins[rel="stateprovince"] {
    background-position: -32px 0px;
}
#legend ins[rel="regiondistrict"] {
    background-position: -48px 0px;
}
#legend ins[rel="locality"] {
    background-position: -64px 0px;
}
</style>

<br>
<div id="legend">
    <table class="jstree">
        <tr><th colspan="2">Legend</th></tr>
        <tr><td><ins rel="globalregion"></ins></td><td>Global Region</td></tr>
        <tr><td><ins rel="country"></ins></td><td>Country</td></tr>
        <tr><td><ins rel="stateprovince"></ins></td><td>State/province</td></tr>
        <tr><td><ins rel="regiondistrict"></ins></td><td>Region/district</td></tr>
        <tr><td><ins rel="locality"></ins></td><td>Locality</td></tr>
    </table>
</div>

<div id="instructions">
    <h2>Instructions</h2>
    <ul><li>
        <p>
            The number in brackets is the number of items in that location.
        </p>
        <p>
            Drag locations to sort the hierarchy.
        </p>
        <p>
            Locations must stay at the same level (ie. a country cannot become a state).
        </p>
        <p>
            Locations cannot be merged. Move the finer level locations instead.
        </p>
        <p>
            Right click to <em>rename</em>, <em>create</em> or <em>delete</em> locations. A location can only be deleted if there are no items recorded as being in that location.
        </p>
        <p>
            Double click to view the public page and associated items for a location.
        </p>
</div>


{% endblock %}

templates/location/place_dups_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Places</h1>


<table><tr>
        <th>Geoname ID</th><th>Count</th>
    </tr>
{% for place in places %}

<tr><td>
        <a href="gn/{{place.gn_id}}">{{place.gn_id}}</a>
</td><td>
 {{place.count}}
 </td><td>
 </td></tr>
{% endfor %}
</table>



{% endblock %}

templates/location/place_geoname.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Places</h1>


<table><tr>
        <th>Place</th><th>Num Objects</th>
    </tr>
{% for place in places %}

<tr><td>
        <a href="gn/{{place.gn_id}}">{{place}}</a>
</td><td>
 {{place.museumobject_set.count}}
 </td><td>
 </td></tr>
{% endfor %}
</table>



{% endblock %}

templates/location/place_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Places</h1>


<table><tr>
        <th>Name</th><th>Objects</th>
    </tr>
{% for place in place_list %}

<tr><td>
<a href="{{place.get_absolute_url}}">{{place}}</a>
</td><td>
 {{place.museumobject_set.count}}
 </td><td>
 </td></tr>
{% endfor %}
</table>



{% endblock %}

templates/location/region_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Regions</h1>


<table><tr>
        <th>Name</th><th>Objects</th>
    </tr>
{% for region in regions %}

<tr><td>
    {% url region_list region.region as the_url %}
    <a href="{{ the_url }}">{{region.region}}</a>
</td><td>
    {{region.count}}
</td></tr>
{% endfor %}
</table>



{% endblock %}

templates/location/tree_view.html
<ul>
{% for gr in global_regions %}
  <li>{{gr.name}}
    <ul>
      {% for country in gr.country_set.all %}
      <li>{{country.name}}
      <ul>
        {% for sp in country.stateprovince_set.all %}
        <li>{{sp.name}}
          <ul>
            {% for rd in sp.regiondistrict_set.all %}
            <li>{{rd.name}}
                <ul>
                {% for locality in rd.locality_set.all %}
                <li>{#<a href="{% url admin:location_locality_change locality.id %}">#}{{locality.name}}{#</a>#}</li>
                {% endfor %}
              </ul>
            </li>
            {% endfor %}

          </ul>
        </li>
        {% endfor %}
      </ul>
      </li>
      {% endfor %}
    </ul>
  </li>
{% endfor %}
<ul>

templates/location/tree_view_table.html
<html>
<head>
  <style>
table {
  border-collapse:collapse;
}
table,th, td {
  border: 1px solid black;
}
  </style>
  </head>
<body>

<table>
  <tr><th>Global region</th><th>Country</th><th>State/province</th><th>Region/district</th><th>Locality</th></tr>
{% for gr in global_regions %}
<tr><td>{{gr.name}}</td></tr>
  {% for country in gr.country_set.all %}
  <tr><td>&nbsp;</td><td><a href="{% url admin:location_country_change country.id %}">{{country.name}}</a></td></tr>
    {% for sp in country.stateprovince_set.all %}
    <tr><td colspan="2">&nbsp;</td><td><a href="{% url admin:location_stateprovince_change sp.id %}">{{sp.name}}</a></td></tr>
      {% for rd in sp.regiondistrict_set.all %}
      <tr><td colspan="3">&nbsp;</td><td>
        <a href="{% url admin:location_regiondistrict_change rd.id %}">{{rd.name}}</a></td></tr>
        {% for locality in rd.locality_set.all %}
        <tr><td colspan="4">&nbsp;</td><td><a href="{% url admin:location_locality_change locality.id %}">{{locality.name}}</a></td></tr>
        {% endfor %}
      {% endfor %}
    {% endfor %}
  {% endfor %}
{% endfor %}
</table>

</body>
</html>