cat/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView
from cat.models import MuseumObject


urlpatterns = patterns('cat.views',

    url(r'^item/$',
        ListView.as_view(
            model=MuseumObject, paginate_by=20), name='artefact_list'),
    url(r'^item/(?P<reg_num>\d+)$', 'item_detail', name='artefact_view'),



    url(r'^categories/$', 'categories_browse', name='categories_list'),

    url(r'^categories/(?P<full_slug>.+)/$', 'categories_list',
        name='categories_list'),

    url(r'^itemtype/(?P<category>.+)/(?P<item_name>.+)/$', 'item_type_list',
        name='item_type_list'),

)

common/views.py
from haystack.views import FacetedSearchView
from django import forms
from haystack.forms import SearchForm
from django.core.exceptions import ValidationError
import logging

logger = logging.getLogger(__name__)

from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape
from django.forms import CheckboxInput
from django.utils.safestring import mark_safe
from django.views.generic import TemplateView
from common.models import SiteConfiguration


class ExpandableCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, choices=(), num_before_fold=5):
        if value is None:
            value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = [u'<ul>']
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])

        choices = self.choices + list(choices)

        selected_choices = [choice for choice in choices if choice[0] in str_values]
        choices = [choice for choice in choices if choice[0] not in str_values]

        for i, (option_value, option_label) in enumerate(selected_choices):
            self.render_checkbox(output, has_id, final_attrs,
                attrs, i, str_values, option_value, name, option_label)

        for i, (option_value, option_label) in enumerate(choices[:num_before_fold], start=len(selected_choices)):
            self.render_checkbox(output, has_id, final_attrs,
                attrs, i, str_values, option_value, name, option_label)

        output.append(u'</ul>')

        if choices[num_before_fold:]:
            output.append(u'<ul class="extra-options">')

            for i, (option_value, option_label) in enumerate(choices[num_before_fold:], start=(len(selected_choices) + num_before_fold)):
                self.render_checkbox(output, has_id, final_attrs,
                    attrs, i, str_values, option_value, name, option_label)
            output.append(u'</ul>')

            output.append(u'<a href="#" class="display-more">more...</a>')

        return mark_safe(u'\n'.join(output))

    def render_checkbox(self, output, has_id, final_attrs, attrs, i, str_values, option_value, name, option_label):
        # If an ID attribute was given, add a numeric index as a suffix,
        # so that the checkboxes don't all have the same ID attribute.
        if has_id:
            final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
            label_for = u' for="%s"' % final_attrs['id']
        else:
            label_for = ''

        cb = CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
        option_value = force_unicode(option_value)
        rendered_cb = cb.render(name, option_value)
        option_label = conditional_escape(force_unicode(option_label))
        output.append(u'<li><label%s>%s %s</label></li>' % (label_for, rendered_cb, option_label))


class UnvalidatedMultipleChoiceField(forms.MultipleChoiceField):
    widget = ExpandableCheckboxSelectMultiple

    def validate(self, value):
        """
        Validates that the input is a list or tuple.
        """
        if self.required and not value:
            raise ValidationError(self.error_messages['required'])


class CatalogueSearchForm(SearchForm):
    category = UnvalidatedMultipleChoiceField(required=False)
    global_region = UnvalidatedMultipleChoiceField(required=False)
    country = UnvalidatedMultipleChoiceField(required=False)
    item_name = UnvalidatedMultipleChoiceField(required=False)
    person = forms.CharField(required=False)
    has_images = forms.BooleanField(required=False, label="Only return results with an associated image")

    # def __init__(self, *args, **kwargs):
    #     self.item_names = kwargs.pop("item_names", [])

    #     super(CatalogueSearchForm, self).__init__(*args, **kwargs)


class PersistentSearchView(FacetedSearchView):
    __name__ = "PersistentSearchView"

    def extra_context(self):
        """
        Save results to session
        """
        extra = super(PersistentSearchView, self).extra_context()

        if self.form.is_valid():
            self.request.session['search_query'] = self.form.cleaned_data
            self.request.session['search_facets'] = self.form.selected_facets
        if self.results:
            # Access the first result to prevent ZeroDivisionError
            self.results[0]
        self.request.session['search_results'] = self.results
        self.request.session['search_results_per_page'] = self.results_per_page
        return extra

from django.core.paginator import Paginator, InvalidPage
from haystack.query import EmptySearchQuerySet
from django.conf import settings
from django.shortcuts import render
from django.http import Http404
from haystack.query import SearchQuerySet

RESULTS_PER_PAGE = getattr(settings, 'HAYSTACK_SEARCH_RESULTS_PER_PAGE', 21)


def catalogue_search(request, template='search/search.html', load_all=True,
    form_class=CatalogueSearchForm, searchqueryset=None, extra_context=None,
    results_per_page=None):
    """
    A more traditional view that also demonstrate an alternative
    way to use Haystack.

    Useful as an example of for basing heavily custom views off of.

    Also has the benefit of thread-safety, which the ``SearchView`` class may
    not be.

    Template:: ``search/search.html``
    Context::
        * form
          An instance of the ``form_class``. (default: ``ModelSearchForm``)
        * page
          The current page of search results.
        * paginator
          A paginator instance for the results.
        * query
          The query received by the form.
    """
    query = ''
    results = EmptySearchQuerySet()
    results_per_page = results_per_page or RESULTS_PER_PAGE

    if request.GET.get('q'):
        form = form_class(request.GET, searchqueryset=searchqueryset, load_all=load_all)

        if form.is_valid():
            query = form.cleaned_data['q']
            results = form.search()
    else:
        form = form_class(searchqueryset=searchqueryset, load_all=load_all)

    results = results.facet('categories').facet('country').facet('has_images').facet('global_region').facet('item_name')

    if form.is_valid():
        results = filter_with_facet(form, results, 'item_name', 'item_name')
        results = filter_with_facet(form, results, 'category', 'categories')
        results = filter_with_facet(form, results, 'global_region', 'global_region')
        results = filter_with_facet(form, results, 'country', 'country')

        if form.cleaned_data['person']:
            sqs = SearchQuerySet()
            for p in form.cleaned_data['person'].split():
                term = sqs.query.clean(p)
                results = results.narrow(u'people:"%s"' % term)

        if form.cleaned_data['has_images'] == True:
            results = results.narrow(u'has_images_exact:true')

    facets = results.facet_counts()

    if facets:
        # Prepare the form with all the available facets
        load_facets_into_form(form, facets, 'item_name', 'item_name')
        load_facets_into_form(form, facets, 'category', 'categories')
        load_facets_into_form(form, facets, 'global_region', 'global_region')
        load_facets_into_form(form, facets, 'country', 'country')

        # Append count of images into form
        appended_count = False
        for name, val in facets['fields']['has_images']:
            if name == 'true':
                form.fields['has_images'].label += ' (%s)' % val
                appended_count = True
        if not appended_count:
            form.fields['has_images'].label += ' (0)'

    results = results.order_by('registration_number')

    paginator = Paginator(results, results_per_page)

    try:
        page = paginator.page(int(request.GET.get('page', 1)))
    except InvalidPage:
        raise Http404("No such page of results!")

    context = {
        'form': form,
        'page': page,
        'paginator': paginator,
        'query': query,
        'suggestion': None,
        'facets': facets,
    }

    # Store query for paging through results on item detail page
    if form.is_valid():
        request.session['search_query'] = form.cleaned_data
    # Access the first result to prevent ZeroDivisionError
    if results:
        results[0]
    request.session['search_results'] = results
    request.session['search_results_per_page'] = results_per_page

    if getattr(settings, 'HAYSTACK_INCLUDE_SPELLING', False):
        context['suggestion'] = form.get_suggestion()

    if extra_context:
        context.update(extra_context)

    return render(request, template, context)


def filter_with_facet(form, results, form_field_name, facet_name):
    if form.cleaned_data[form_field_name]:
        ins = None
        for itn in form.cleaned_data[form_field_name]:
            if ins:
                ins += u' AND '
            else:
                ins = u''
            ins += u'"%s"' % results.query.clean(itn)

        results = results.narrow(facet_name + u'_exact:%s' % ins)

    return results


def load_facets_into_form(form, facets, form_field_name, facet_name):
    if 'fields' in facets and facet_name in facets['fields']:
        form.fields[form_field_name].choices = [
            (facet[0], "%s (%s)" % (facet[0], facet[1]))
                for facet in facets['fields'][facet_name]]


class HomepageView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(HomepageView, self).get_context_data(**kwargs)

        # Add to the context
        results = SiteConfiguration.objects.all()

        if len(results) > 0:
            site_config = results[0]

            context['site_config'] = site_config
            context['new_acquisition'] = site_config.new_acquisition

templates/search/search.html
{% extends 'base_wide.html' %}

{% block title %}Search | {{block.super}}{% endblock %}

{% block content %}


<div class="search-results-head results-head">
    <h2>Search Results</h2>
    <div class="grid-list-selector">
		<div class="display-as">Display as:</div>
		<button class="list" title="List View">List View</button>
		<button class="grid" title="Grid View">Grid View</button>
	</div>
	<div class="pagination">
		{% load paginator %}{% paginator 4 extra_class="top" %}
		<div class="results-count">Results {{page.start_index}} to {{page.end_index}} of {{page.paginator.count}}</div>
	</div>
</div><!-- /search-results-head -->

<!-- Begin faceting. -->
<div class="filter-bar">
<form id="filter-form">
    <div class="filter-clear">
        <p>Filter results: 
        <button type="button" class="btn">Clear</button>
        </p>
    </div>
<h2>By Category</h2>
    <div>
        <dl>
            <dt>Categories</dt>
            {% if form.category %}
                <dd>
                    {{ form.category }}
                </dd>
            {% else %}
                <dd>None</dd>
            {% endif %}
        </dl>
    </div>
    <div>
        <dl>
            <dt>Item name</dt>
            {% if form.item_name %}
                <dd>
                    {{ form.item_name }}
                </dd>
            {% else %}
                <dd>None</dd>
            {% endif %}
        </dl>
    </div>
<h2>Places</h2>
    <div>
        <dl>
            <dt>Global region</dt>
            {% if form.global_region %}
                <dd>
                    {{ form.global_region }}
                </dd>
            {% else %}
                <dd>None</dd>
            {% endif %}
        </dl>
    </div>
    <div>
        <dl>
            <dt>Country</dt>
            {% if form.country %}
                <dd>
                    {{ form.country }}
                </dd>
            {% else %}
                <dd>None</dd>
            {% endif %}
        </dl>
    </div>
<h2>People</h2>
    <div>
        <dl>
            {{form.person}}
        </dl>
    </div>
    <div>
        <dl>
            <dt> </dt>
            <dd><ul><li>
                <label for="id_has_images">
                {{ form.has_images }}{{ form.has_images.label }}
            </label></li></ul>
            </dd>
        </dl>
    </div>
</form>
</div>

    <!-- End faceting -->
<div class="search-results">
{% if query %}
<div class="item-listing list-view">
    <table id="item-listing-table">
        <tr><th></th><th>Item</th><th>Category</th><th>Place</th></tr>
        {% load uqam %}
    {% for result in page.object_list %}
        {% add_search_results_param result.list_row forloop.counter0 page.start_index %}
    {% empty %}
        <tr><td colspan="4">No results found.</td></tr>
    {% endfor %}
    </table>

</div><!-- /search-results /list-view -->
<div id="item-listing-grid" class="grid-view">
    <ul>
        {% for result in page.object_list %}
            {% add_search_results_param result.grid_element forloop.counter0 page.start_index %}
        {% endfor %}
    </ul>
</div><!-- /item-listing-grid -->
{% else %}
    {# Show some example queries to run, maybe query syntax, something else? #}
    <p class="no-results">Use the search options above or browse by categories, people, or places to view the collection.</p>
{% endif %}
</div>

{% paginator 4 extra_class="bottom" %}

{% endblock %}



{% block javascript %}
{{block.super}}
<script type="text/javascript">
$(document).ready(function () {
    // Fix up item links with search-result identifier
    $('#item-listing-table a[href*="/item/"]');



    function copyAndSubmit(event) {
        $('#main-search :input').attr("disabled", "disabled");
        $('#main-search-q').removeAttr("disabled");
        $('#filter-form :checked').clone().hide().appendTo('form#main-search');

        if ($('#id_person').val() !== "") {
            $('#filter-form :text').clone().hide().appendTo('form#main-search');
        }

        $('form#main-search').submit();
    }

    $('#filter-form :checkbox').click(copyAndSubmit);
    $('#filter-form').submit(function(event) {
        event.preventDefault();
        copyAndSubmit();
    });

    $('.extra-options').hide();

// Display More in filter bar
    $('.filter-bar a.display-more').click(function(event) {
        event.preventDefault();
        var extra = $(this).prev();
        if (extra.is(':visible')) {
            extra.slideUp();
            $(this).text('more...')
        } else {
            $(this).text('less...');
            extra.slideDown();
        }
    });

// Clear filters
    $('.filter-clear button').click(function(event) {
        $('#main-search :input').attr("disabled", "disabled");
        $('#main-search-q').removeAttr("disabled");

        $('form#main-search').submit();
    });


});
</script>
{% endblock javascript %}